# Generated by Django 4.0.5 on 2022-07-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caterogy',
            new_name='category',
        ),
    ]
